spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/franchise
    username: franchise_user
    password: franchise_pass

  jpa:
    hibernate:
      ddl-auto: validate

  flyway:
    enabled: true
    locations: classpath:db/migration

app:
  fixed-date: 2025-09-01
  jwt:
    secret: "CHANGE_ME_TO_A_LONG_RANDOM_SECRET_KEY_32BYTES_MINIMUM"
    access-token-exp-minutes: 60
    cookie:
      name: "ACCESS_TOKEN"
      secure: false      # 로컬 http면 false, 배포 https면 true
      same-site: "Lax"   # SPA+서버 분리 + https 배포면 "None" 고려(그땐 secure=true 필수)


logging:
  level:
    org.springframework.security: DEBUG

fastapi:
  base-url: http://localhost:8000
